# This is a basic workflow to help you get started with Actions

name: github-action-IAC-scanning
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan-IAC:
    runs-on: ubuntu-latest
    container:
      image: dayakar18/githubaction:latest
      steps:
        - uses: actions/checkout@v2
      
